import gql from 'graphql-tag'

export const FinancialRatiosSchema = gql`
  type FinancialRatioTTM {
    dividendYielTTM: Float
    dividendYielPercentageTTM: Float
    peRatioTTM: Float
    pegRatioTTM: Float
    payoutRatioTTM: Float
    currentRatioTTM: Float
    quickRatioTTM: Float
    cashRatioTTM: Float
    daysOfSalesOutstandingTTM: Float
    daysOfInventoryOutstandingTTM: Float
    operatingCycleTTM: Float
    daysOfPayablesOutstandingTTM: Float
    cashConversionCycleTTM: Float
    grossProfitMarginTTM: Float
    operatingProfitMarginTTM: Float
    pretaxProfitMarginTTM: Float
    netProfitMarginTTM: Float
    effectiveTaxRateTTM: Float
    returnOnAssetsTTM: Float
    returnOnEquityTTM: Float
    returnOnCapitalEmployedTTM: Float
    netIncomePerEBTTTM: Float
    ebtPerEbitTTM: Float
    ebitPerRevenueTTM: Float
    debtRatioTTM: Float
    debtEquityRatioTTM: Float
    longTermDebtToCapitalizationTTM: Float
    totalDebtToCapitalizationTTM: Float
    interestCoverageTTM: Float
    cashFlowToDebtRatioTTM: Float
    companyEquityMultiplierTTM: Float
    receivablesTurnoverTTM: Float
    payablesTurnoverTTM: Float
    inventoryTurnoverTTM: Float
    fixedAssetTurnoverTTM: Float
    assetTurnoverTTM: Float
    operatingCashFlowPerShareTTM: Float
    freeCashFlowPerShareTTM: Float
    cashPerShareTTM: Float
    operatingCashFlowSalesRatioTTM: Float
    freeCashFlowOperatingCashFlowRatioTTM: Float
    cashFlowCoverageRatiosTTM: Float
    shortTermCoverageRatiosTTM: Float
    capitalExpenditureCoverageRatioTTM: Float
    dividendPaidAndCapexCoverageRatioTTM: Float
    priceBookValueRatioTTM: Float
    priceToBookRatioTTM: Float
    priceToSalesRatioTTM: Float
    priceEarningsRatioTTM: Float
    priceToFreeCashFlowsRatioTTM: Float
    priceToOperatingCashFlowsRatioTTM: Float
    priceCashFlowRatioTTM: Float
    priceEarningsToGrowthRatioTTM: Float
    priceSalesRatioTTM: Float
    dividendYieldTTM: Float
    enterpriseValueMultipleTTM: Float
    priceFairValueTTM: Float
    dividendPerShareTTM: Float
  }

  type FinancialRatios {
    symbol: String
    date: String
    period: Period
    currentRatio: Float
    quickRatio: Float
    cashRatio: Float
    daysOfSalesOutstanding: Float
    daysOfInventoryOutstanding: Float
    operatingCycle: Float
    daysOfPayablesOutstanding: Float
    cashConversionCycle: Float
    grossProfitMargin: Float
    operatingProfitMargin: Float
    pretaxProfitMargin: Float
    netProfitMargin: Float
    effectiveTaxRate: Float
    returnOnAssets: Float
    returnOnEquity: Float
    returnOnCapitalEmployed: Float
    netIncomePerEBT: Float
    ebtPerEbit: Float
    ebitPerRevenue: Float
    debtRatio: Float
    debtEquityRatio: Float
    longTermDebtToCapitalization: Float
    totalDebtToCapitalization: Float
    interestCoverage: Float
    cashFlowToDebtRatio: Float
    companyEquityMultiplier: Float
    receivablesTurnover: Float
    payablesTurnover: Float
    inventoryTurnover: Float
    fixedAssetTurnover: Float
    assetTurnover: Float
    operatingCashFlowPerShare: Float
    freeCashFlowPerShare: Float
    cashPerShare: Float
    payoutRatio: Float
    operatingCashFlowSalesRatio: Float
    freeCashFlowOperatingCashFlowRatio: Float
    cashFlowCoverageRatios: Float
    shortTermCoverageRatios: Float
    capitalExpenditureCoverageRatio: Float
    dividendPaidAndCapexCoverageRatio: Float
    dividendPayoutRatio: Float
    priceBookValueRatio: Float
    priceToBookRatio: Float
    priceToSalesRatio: Float
    priceEarningsRatio: Float
    priceToFreeCashFlowsRatio: Float
    priceToOperatingCashFlowsRatio: Float
    priceCashFlowRatio: Float
    priceEarningsToGrowthRatio: Float
    priceSalesRatio: Float
    dividendYield: Float
    enterpriseValueMultiple: Float
    priceFairValue: Float
  }
`
