import type { NextPage } from 'next'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import CheckoutCTA from '../components/checkout/CheckoutCTA'
import Header from '../components/header/Header'
import LandingCard from '../components/Landing/LandingCard'
import LandingPreview from '../components/Landing/LandingPreview'
import { BaseGrid } from '../components/UI/Grid'
import Warning from '../components/Warning'

const Home: NextPage = () => {
  const { data, status } = useSession()
  if (status === 'loading') {
    return (
      <h1 css={{ gridColumn: '1/-1' }}>
        <p css={{ fontSize: 16 }}>Loading...</p>
      </h1>
    )
  }
  if (status === 'unauthenticated') {
    return (
      <>
        <Header />
        <BaseGrid>
          <LandingPreview />
        </BaseGrid>
      </>
    )
  }
  if (status === 'authenticated' && !data.user.isActive) {
    return (
      <>
        <Header />
        <BaseGrid>
          <Warning />
          <CheckoutCTA />
        </BaseGrid>
      </>
    )
  }

  return (
    <div>
      <Head>
        <title>Valuemap</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <BaseGrid>
        <LandingCard />
      </BaseGrid>
    </div>
  )
}

export default Home
